"""Add ESPStatus table

Revision ID: b653ff540e40
Revises: 090045684e0e
Create Date: 2024-07-08 01:53:53.391503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b653ff540e40'
down_revision = '090045684e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esp_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rssi', sa.Integer(), nullable=False),
    sa.Column('packet_loss', sa.Float(), nullable=False),
    sa.Column('uptime', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esp_status')
    # ### end Alembic commands ###
